# fly.toml app configuration file generated for pysatellite-blog-dhkdtld37 on 2024-02-19T17:26:12+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pysatellite-blog-dhkdtld37'
primary_region = 'nrt'

[build]
  images = "pysatellite/blog-tomsawyer:latest"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
